server:
  port: 8081
application:
  name: conta
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/conta
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  kafka:
    producer:
      bootstrap-servers: 127.0.0.1:9092
      key-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: conta
topic:
  name:
    producer: NOVA_CONTA
